# Generated by Django 3.1.7 on 2021-04-06 16:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assess', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_body', models.CharField(max_length=200)),
                ('ques_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assess.course')),
            ],
        ),
        migrations.CreateModel(
            name='responses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chosen_response', models.CharField(max_length=100)),
                ('status', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('time_taken', models.TimeField()),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assess.candidate')),
                ('q_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assess.question')),
            ],
        ),
        migrations.CreateModel(
            name='options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optA', models.CharField(max_length=100)),
                ('optB', models.CharField(max_length=100)),
                ('optC', models.CharField(max_length=100)),
                ('optD', models.CharField(max_length=100)),
                ('correct_opt', models.IntegerField(validators=[django.core.validators.MaxValueValidator(4), django.core.validators.MinValueValidator(1)])),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assess.course')),
                ('ques_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assess.question')),
            ],
        ),
        migrations.CreateModel(
            name='assessments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_fname', models.CharField(max_length=20)),
                ('candidate_lname', models.CharField(max_length=20)),
                ('date_of_assess', models.DateTimeField()),
                ('score', models.IntegerField()),
                ('total_time', models.TimeField()),
                ('assess_course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assess.course')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assess.candidate')),
            ],
        ),
    ]
